name: Build and Release Desktop Application

on:
  push:
    branches:
      - "*.x"
    tags:
      - "v*.*.*"

permissions:
  contents: write
  
jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'
        
    - name: Restore NuGet packages
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Publish
      run: dotnet publish .\TicTakGame\TicTakGame.csproj --configuration Release --output publish
      
    - name: Create ZIP file
      run: Compress-Archive -Path ./publish/* -DestinationPath ${{ github.event.repository.name }}-${{ github.ref_name }}-windows-x86_64.zip
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ github.event.repository.name }}-${{ github.ref_name }}-windows-x86_64.zip
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.ref_name }}
        path: ${{ github.event.repository.name }}-${{ github.ref_name }}-windows-x86_64.zip
        if-no-files-found: error
